# Generated by Django 2.1.7 on 2019-08-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
